#!/usr/bin/env bash
#a Bash script that displays the content of the file /etc/passwd
passwd_file="/etc/passwd"

# Use a while loop to read each line from the file
while IFS=: read -r username _ uid _ _ home _
do
    # Display the desired information
    echo "$username:$uid:$home" 

# Redirect input from the file to the loop
done < "$passwd_file"
