#!/usr/bin/env bash
#a Bash script that displays the content of the file /etc/passwd
passwd_file="/etc/passwd"
while IFS=: read -r username _ _ gid info home shell
do
	password_info=$(awk -F: -v user="$username" '$1 == user { print $2 }' /etc/shadow)
	
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $gid's place is protected by the passcode $password_info, more info about the user here: $info"
done < "$passwd_file"
